id: ID09DB0BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:05:01+00:00'
last_modified: '2022-06-08T12:58:49.745979+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10319
  title: བཀའ་གདམས་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0066':
      image_group_id: I1GS105591
      title: Volume 1 of bka' gdams chos 'byung
      total_pages: 206
      order: 1
      base_file: 0066.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
