id: P006959
initial_creation_type: ocr
source_metadata:
  id: bdr:W10319
  title: བཀའ་གདམས་ཆོས་འབྱུང
  author: ''
  volumes:
    cee7b0f663294ecabbbc2a8d3f7535cd:
      image_group_id: I1GS105591
      title: ''
      volume_number: 1
      total_pages: 206
ebook_metadata:
  title: བཀའ་གདམས་ཆོས་འབྱུང
  author: ''
  sku: P006959
  cover: cover.jpg
  layers:
  - pagination
