id: P006959
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:32:57.089862
source_metadata:
  id: bdr:W10319
  title: བཀའ་གདམས་ཆོས་འབྱུང
  author: ''
  volumes:
    93540eadb460480fb286010540828419:
      image_group_id: I1GS105591
      title: Volume 1 of bka' gdams chos 'byung
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
