id: opecha:P006959
initial_creation_type: ocr
source_metadata:
  id: bdr:W10319
  title: བཀའ་གདམས་ཆོས་འབྱུང
  volume:
    93540eadb460480fb286010540828419:
      image_group_id: I1GS105591
      title: Volume 1 of bka' gdams chos 'byung
      volume_number: 1
      total_pages: 206
  author: ''
ebook_metadata:
  title: བཀའ་གདམས་ཆོས་འབྱུང
  author: ''
  sku: P006959
  cover: cover.jpg
  layers:
  - pagination
